//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormitoryWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public booking()
        {
            this.Current_in = new HashSet<Current_in>();
        }
    
        public int booking_id { get; set; }
        public string customer_id { get; set; }
        public int room_id { get; set; }
        public Nullable<System.DateTime> date_in { get; set; }
        public string File { get; set; }
        public string status { get; set; }
        public string Email { get; set; }
        public IEnumerable<Room> roomlist { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Room Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Current_in> Current_in { get; set; }
    }
}
